[theme]
base="light"

[server]
port = 8051
baseUrlPath = "streamlit-gpt-experimentations"
enableWebsocketCompression = false
sslCertFile="ssl/localhost.crt"
sslKeyFile="ssl/localhost.key"

[browser]
serverAddress = "0.0.0.0"
